[LightDM]
start-default-seat=true
logind-check-graphical=false

[Seat:seat0]
greeter-session=cardputer-zero-pi-greeter-labwc
autologin-guest=false
autologin-user=
autologin-session=
autologin-user-timeout=0
